export const MYSQL_PROVIDER = 'MYSQL_PROVIDER';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CLINIC_REPOSITORY = 'CLINIC_REPOSITORY';
export const MEDICINE_REPOSITORY = 'MEDICINE_REPOSITORY';
export const DOCTOR_DIAGNOSIS_REPOSITORY = 'DOCTOR_DIAGNOSIS_REPOSITORY';
export const SELF_THERAPY_REPOSITORY = 'SELF_THERAPY_REPOSITORY';
export const TREATMENT_PACKET_REPOSITORY = 'TREATMENT_PACKET_REPOSITORY';
export const THERAPY_REPOSITORY = 'THERAPY_REPOSITORY';
export const MERIDIAN_REPOSITORY = 'MERIDIAN_REPOSITORY';
export const COMPLAINT_REPOSITORY = 'COMPLAINT_REPOSITORY';
export const STOMACH_CHECKUP_REPOSITORY = 'STOMACH_CHECKUP_REPOSITORY';
export const PATIENT_REPOSITORY = 'PATIENT_REPOSITORY';

export const PAGINATION_DEFAULT_LIMIT = 10;

export const PUBLIC_ROUTE = 'PUBLIC_ROUTE';

export const RM_PREFIX = 'MS';
