export const MYSQL_PROVIDER = 'MYSQL_PROVIDER';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CLINIC_REPOSITORY = 'CLINIC_REPOSITORY';
export const MEDICINE_REPOSITORY = 'MEDICINE_REPOSITORY';

export const PAGINATION_DEFAULT_LIMIT = 10;

export const PUBLIC_ROUTE = 'PUBLIC_ROUTE';
