export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CLINIC_REPOSITORY = 'CLINIC_REPOSITORY';
export const MEDICINE_REPOSITORY = 'MEDICINE_REPOSITORY';
export const DOCTOR_DIAGNOSIS_REPOSITORY = 'DOCTOR_DIAGNOSIS_REPOSITORY';
export const SELF_THERAPY_REPOSITORY = 'SELF_THERAPY_REPOSITORY';
export const TREATMENT_PACKET_REPOSITORY = 'TREATMENT_PACKET_REPOSITORY';
export const THERAPY_REPOSITORY = 'THERAPY_REPOSITORY';
export const MERIDIAN_REPOSITORY = 'MERIDIAN_REPOSITORY';
export const COMPLAINT_REPOSITORY = 'COMPLAINT_REPOSITORY';
export const STOMACH_CHECKUP_REPOSITORY = 'STOMACH_CHECKUP_REPOSITORY';
export const TONGUE_CHECKUP_REPOSITORY = 'TONGUE_CHECKUP_REPOSITORY';
export const PATIENT_REPOSITORY = 'PATIENT_REPOSITORY';
export const DURATION_ADVICE_REPOSITORY = 'DURATION_ADVICE_REPOSITORY';
export const TREATMENT_REPOSITORY = 'TREATMENT_REPOSITORY';
export const TREATMENT_DOCTOR_DIAGNOSIS_REPOSITORY =
  'TREATMENT_DOCTOR_DIAGNOSIS_REPOSITORY';
export const TREATMENT_MEDICINE_REPOSITORY = 'TREATMENT_MEDICINE_REPOSITORY';
export const TREATMENT_THERAPY_HISTORY_REPOSITORY =
  'TREATMENT_THERAPY_HISTORY_REPOSITORY';
export const TREATMENT_COMPLAINT_REPOSITORY = 'TREATMENT_COMPLAINT_REPOSITORY';
export const TREATMENT_STOMACH_CHECKUP_REPOSITORY =
  'TREATMENT_STOMACH_CHECKUP_REPOSITORY';
export const TREATMENT_TONGUE_CHECKUP_REPOSITORY =
  'TREATMENT_TONGUE_CHECKUP_REPOSITORY';
export const TREATMENT_PULSE_CHECKUP_REPOSITORY =
  'TREATMENT_PULSE_CHECKUP_REPOSITORY';
export const TREATMENT_THERAPY_REPOSITORY = 'TREATMENT_THERAPY_REPOSITORY';
export const TREATMENT_SELF_THERAPY_REPOSITORY =
  'TREATMENT_SELF_THERAPY_REPOSITORY';
export const ABSENCE_REPOSITORY = 'ABSENCE_REPOSITORY';
export const SETTING_REPOSITORY = 'SETTING_REPOSITORY';
